### ISSUE TITLE
token保存的问题

### ISSUE THREAD

**Issue by HerryLo** [Hzy0913/blog-server#1]
[routes的auth.js](https://github.com/Hzy0913/blog-server/blob/master/routes/auth.js)

在用jwt 生成token，那你的token保存在哪里额？

**Comment by HerryLo** [comment]
希望可以交流一下

**Comment by HerryLo** [comment]
用jwt 生成token的作用是啥哦

**Comment by Hzy0913** [comment]
@HerryLo   token验证账号密码以后服务端生成并且响应给客户端，由客户端保存，toekn配置里可以设置过期时间，类似session过期时间，过期后不可用。需要验证权限的接口，前端请求的时候需要请求头里带上token，服务端接到token后验证是否正确即可，token里可以携带一些参数比如用户id，可以用来判断是哪个用户。token不保存在服务端，由客户端保存(loaclstorage)所以可以减轻服务端压力。

**Comment by HerryLo** [comment]
jwt 做的事就是 生成token，验证 token 是否失效。

**Comment by HerryLo** [comment]
那在这里Redis 的作用是什么尼，我看到你里面还是用了 Redis ？？@Hzy0913

**Comment by Hzy0913** [comment]
@HerryLo  存储session
