### ISSUE TITLE
数据库存的应该是加密后的密码

### ISSUE THREAD

**Issue by lydat** [Hzy0913/blog-server#2]
数据库存的应该是加密后的密码，我看你这个存的好像是直接用户的密码，这样安全性有保证吗？

**Comment by lydat** [comment]
而且我觉得jwt生成的token应该是可变的，不然别人拿到token不是可以伪造数据吗，你这个好像是固定的？

**Comment by Hzy0913** [comment]
@配置里存的密码是md5以后的，你可以手动md5一个密码存进去，token是每次登录都会变的，不是固定的
